//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cede_ASP_MVC_Events_Main.wsPersonalService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PersonalDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid PersonalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private System.Nullable<bool> IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid PersonalId {
            get {
                return this.PersonalIdField;
            }
            set {
                if ((this.PersonalIdField.Equals(value) != true)) {
                    this.PersonalIdField = value;
                    this.RaisePropertyChanged("PersonalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<bool> IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsPersonalService.PersonalServiceSoap")]
    public interface PersonalServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetPersonalResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonal", ReplyAction="*")]
        Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalResponse GetPersonal(Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonal", ReplyAction="*")]
        System.Threading.Tasks.Task<Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalResponse> GetPersonalAsync(Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonal", Namespace="http://tempuri.org/", Order=0)]
        public Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalRequestBody Body;
        
        public GetPersonalRequest() {
        }
        
        public GetPersonalRequest(Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPersonalRequestBody {
        
        public GetPersonalRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonalResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalResponseBody Body;
        
        public GetPersonalResponse() {
        }
        
        public GetPersonalResponse(Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cede_ASP_MVC_Events_Main.wsPersonalService.PersonalDto[] GetPersonalResult;
        
        public GetPersonalResponseBody() {
        }
        
        public GetPersonalResponseBody(Cede_ASP_MVC_Events_Main.wsPersonalService.PersonalDto[] GetPersonalResult) {
            this.GetPersonalResult = GetPersonalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonalServiceSoapChannel : Cede_ASP_MVC_Events_Main.wsPersonalService.PersonalServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonalServiceSoapClient : System.ServiceModel.ClientBase<Cede_ASP_MVC_Events_Main.wsPersonalService.PersonalServiceSoap>, Cede_ASP_MVC_Events_Main.wsPersonalService.PersonalServiceSoap {
        
        public PersonalServiceSoapClient() {
        }
        
        public PersonalServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonalServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalResponse Cede_ASP_MVC_Events_Main.wsPersonalService.PersonalServiceSoap.GetPersonal(Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalRequest request) {
            return base.Channel.GetPersonal(request);
        }
        
        public Cede_ASP_MVC_Events_Main.wsPersonalService.PersonalDto[] GetPersonal() {
            Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalRequest inValue = new Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalRequest();
            inValue.Body = new Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalRequestBody();
            Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalResponse retVal = ((Cede_ASP_MVC_Events_Main.wsPersonalService.PersonalServiceSoap)(this)).GetPersonal(inValue);
            return retVal.Body.GetPersonalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalResponse> Cede_ASP_MVC_Events_Main.wsPersonalService.PersonalServiceSoap.GetPersonalAsync(Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalRequest request) {
            return base.Channel.GetPersonalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalResponse> GetPersonalAsync() {
            Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalRequest inValue = new Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalRequest();
            inValue.Body = new Cede_ASP_MVC_Events_Main.wsPersonalService.GetPersonalRequestBody();
            return ((Cede_ASP_MVC_Events_Main.wsPersonalService.PersonalServiceSoap)(this)).GetPersonalAsync(inValue);
        }
    }
}
