// <auto-generated />
namespace Cede_ASP_API_Events_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Personal_Phone2_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Personal_Phone2_column));
        
        string IMigrationMetadata.Id
        {
            get { return "201905251419017_Personal_Phone2_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
